version: 2
models:
 - name: dim_customer
   description: Customer dimension table
   columns:
     - name: customer_key
       tests:
         - not_null
         - unique
 - name: dim_product
   description: Product dimension table
   columns:
     - name: product_key
       tests:
         - not_null
         - unique
 - name: fact_sales
   description: Sales fact table containing transaction-level data
   columns:
     - name: sales_order_line_key
       tests:
         - not_null
         - unique
     - name: customer_key
       tests:
         - relationships:
             to: ref('dim_customer')
             field: customer_key
     - name: product_key
       tests:
         - relationships:
             to: ref('dim_product')
             field: product_key